config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: "api/v1/sessions" }

  post 'login', to: "api/v1/sessions#create"

  namespace :api do
    namespace :v1 do
      resources :categories
      resources :manufacturers
      resources :products
    end
  end

  root to: 'home#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
  include Orderable
  include TimeFilterable

  has_many :products

  validates_presence_of :name
  validates_uniqueness_of :name
end

app/controllers/api/v1/categories_controller.rb
class Api::V1::CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @categories }
    end
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/new
  # GET /categories/new.json
  def new
    @category = Category.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to api_v1_category_path(@category), notice: 'Kategoria została pomyślnie dodana.' }
        format.json { render json: @category, status: :created, location: @category }
      else
        format.html { render action: "new" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /categories/1
  # PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update_attributes(category_params)
        format.html { redirect_to api_v1_category_path(@category), notice: 'Kategoria została pomyślnie zaktualizowana.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy

    respond_to do |format|
      format.html { redirect_to api_v1_categories_url }
      format.json { head :no_content }
    end
  end

  private

  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @categories }
    end
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @category = Category.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/new
  # GET /categories/new.json
  def new
    @category = Category.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/1/edit
  def edit
    @category = Category.find(params[:id])
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(params[:category])

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render json: @category, status: :created, location: @category }
      else
        format.html { render action: "new" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /categories/1
  # PUT /categories/1.json
  def update
    @category = Category.find(params[:id])

    respond_to do |format|
      if @category.update_attributes(params[:category])
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url }
      format.json { head :no_content }
    end
  end
end

app/views/categories/_form.html.haml
= form_for @category, :html => { :class => "form-horizontal" } do |f|
  - if @category.errors.any?
    #error_explanation
      %h2
        = pluralize(@category.errors.count, "error")
        prohibited this category from being saved:
      %ul
        - @category.errors.full_messages.each do |msg|
          %li= msg
  .control-group
    = f.label :name, :class => "control-label"
    %br/
    .controls
      = f.text_field :name, :class => "input-xlarge"
  .form-actions
    = f.submit t("views.categories.create"), :class => "btn btn-primary"

app/views/categories/edit.html.haml
.page-header
  %h2= t("views.categories.edit") 
= render 'form'
- content_for :sidebar do
  .well
    %ul.nav.nav-list
      %li.nav-header= t("views.shared.sidebar_list_of_options")
      %li.divider
      %li
        = link_to categories_path do
          %i.icon-backward
          = t("views.shared.sidebar_back_to_list")

app/views/categories/new.html.haml
.page-header
  %h2= t("views.categories.create")
= render 'form'
- content_for :sidebar do
  .well
    %ul.nav.nav-list
      %li.nav-header
        = t ("views.shared.sidebar_list_of_options")
      %li.divider
      %li
        = link_to categories_path do
          %i.icon-home
          = t("views.shared.sidebar_back_to_list")